parameters:
  hubdrop.github_username: "%app.github.username%"
  hubdrop.github_organization: "%app.github.organization%"
  hubdrop.github_authorization_key: "%app.github.authorization%"

  hubdrop.drupal_username: "%app.drupal.username%"
  hubdrop.url: "%app.url%"
  hubdrop.jenkins_url: "%app.jenkins_url%"
  hubdrop.paths.home: "/var/hubdrop"

services:
  hubdrop:
    class: HubDrop\Bundle\Service\HubDrop
    arguments: ["%hubdrop.github_username%", "%hubdrop.github_organization%", "%hubdrop.github_authorization_key%", "%hubdrop.drupal_username%", "%hubdrop.url%", "%hubdrop.jenkins_url%", @router, @session]
